### ISSUE TITLE
USER STORY Looking for love

### ISSUE THREAD

**Issue by Damitwhy** [Damitwhy/Going-Bananaz#40]
As a **visitor** I can **find a life partner as diverse as me** so that **I can grow old happy**

## Accepted Criteria:
1. Data base for member details...
2. falls under the data protection act...
3. large storage of members images, profile images, millions of messages daily...

## Tasks: 
- [ ] blah
- [ ] blah
- [ ] Blah

**Comment by Spencily** [comment]
Will not be able to implement this feature at this time, does not fit the purpose of the site.
