### ISSUE TITLE
Bug report spill-over on h2 

### ISSUE THREAD

**Issue by Damitwhy** [Damitwhy/Going-Bananaz#49]
**Describe the bug**
Spill over on accordion-main h2
**To Reproduce**
open landing page with dev tools viewed in Code Institute mobile window 280px * 653px

**Expected behavior**
expected to find all headings fit on page and in containers also social media links

**Screenshots**
![Spill-over2](https://github.com/Damitwhy/Going-Bananaz/assets/159484600/632487cd-4ecb-4c86-a822-e895eafff440)
![Spill-over](https://github.com/Damitwhy/Going-Bananaz/assets/159484600/a0d8cc7b-2a25-480c-88f3-d52170a7c216)

**Additional context**

**Comment by Spencily** [comment]
280 is very small and the smallest you're likely to get according to google dev tools is 320 which fits everything on no problem. I don't think it will be reasonable to focus on this as it shouldn't realistically be an issue so feel like we can close this bug.
