### ISSUE TITLE
User Story 4: Tools for Allyship and Advocacy

### ISSUE THREAD

**Issue by Damitwhy** [Damitwhy/Going-Bananaz#8]
# User Story 4: Tools for Allyship and Advocacy
   - As a visitor, I want to find tools for allyship and advocacy, so that I can actively support marginalized communities.
   - ## Acceptance Criteria:
     - Templates for letters and petitions.
     - Community organizing guides and tips for effective advocacy.
## Tasks:
- [x] Accordion dropdown

**Comment by Spencily** [comment]
Looks great, happy to close
